"""
Alerts service for PotholeIQ.

Endpoints:
  POST /alerts/send    manually alert on a specific pothole (admin key)
  POST /alerts/scan    auto-scan for high-risk unalerted potholes and send (admin key)
  GET  /alerts/history recent alert history from SQLite

Email: SMTP via env vars (SMTP_USER, SMTP_PASS, SMTP_HOST, ALERT_EMAIL_TO).
Fallback: logs to console when SMTP is not configured (safe for demo/dev).
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException

from .auth import verify_admin_key
from .database import insert_alert, get_alert_history, get_high_risk_unalerted, get_conn, POTHOLE_COLS

router = APIRouter(prefix="/alerts", tags=["alerts"])

_SMTP_HOST  = os.getenv("SMTP_HOST",        "smtp.gmail.com")
_SMTP_PORT  = int(os.getenv("SMTP_PORT",    "587"))
_SMTP_USER  = os.getenv("SMTP_USER",        "")
_SMTP_PASS  = os.getenv("SMTP_PASS",        "")
_FROM_EMAIL = os.getenv("ALERT_EMAIL_FROM", _SMTP_USER)
_TO_EMAIL   = os.getenv("ALERT_EMAIL_TO",   "dot.notifications@nyc.gov")

_AUTO_ALERT_THRESHOLD = float(os.getenv("ALERT_RISK_THRESHOLD", "75.0"))


def _send_email(subject: str, body: str) -> bool:
    if not _SMTP_USER or not _SMTP_PASS:
        print(f"[ALERT — no SMTP] {subject}\n{body}")
        return False
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = _FROM_EMAIL
    msg["To"]      = _TO_EMAIL
    msg.attach(MIMEText(body, "plain"))
    try:
        with smtplib.SMTP(_SMTP_HOST, _SMTP_PORT) as s:
            s.ehlo()
            if _SMTP_PORT != 2525:  # Mailtrap sandbox uses port 2525 without STARTTLS
                s.starttls()
            s.login(_SMTP_USER, _SMTP_PASS)
            s.sendmail(_FROM_EMAIL, _TO_EMAIL, msg.as_string())
        return True
    except Exception as e:
        print(f"[ALERT email failed] {e}")
        return False


def _build_alert(pothole: dict, custom_message: Optional[str] = None) -> tuple[str, str]:
    subject = (
        f"[PotholeIQ] {pothole.get('urgency_label','HIGH').upper()} Risk — "
        f"{pothole.get('street_name','Unknown')}, {pothole.get('borough','NYC')}"
    )
    body = f"""
NYC DOT Alert — PotholeIQ Risk Notification
============================================
Pothole ID    : {pothole.get('unique_key')}
Location      : {pothole.get('street_name')}, {pothole.get('borough')}
Status        : {pothole.get('status', 'Open')}
Days Open     : {int(pothole.get('age_days') or 0)} days
Risk Score    : {(pothole.get('risk_score') or 0):.1f} / 100
Urgency       : {pothole.get('urgency_label') or 'N/A'}
Est. Fix Days : {pothole.get('fix_days_estimate', 'N/A')}

Traffic Data
------------
Daily Volume  : {int(pothole.get('traffic_volume') or 0):,} vehicles/day
AADT          : {int(pothole.get('aadt') or 0):,} vehicles/year
Nearby Crashes: {pothole.get('nearby_crashes') or 0} within 200m
Pavement Crash: {'Yes' if pothole.get('pavement_crash_nearby') else 'No'} within 500m

{('Note: ' + custom_message) if custom_message else ''}
Generated by PotholeIQ · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
    """.strip()
    return subject, body


@router.post("/send")
async def send_alert(
    pothole_id: str,
    message:    Optional[str] = None,
    authorized: bool          = Depends(verify_admin_key),
):
    """Send a DOT alert for a specific pothole. Persists to alerts table."""
    with get_conn() as conn:
        row = conn.execute(
            f"SELECT {POTHOLE_COLS} FROM potholes WHERE unique_key = ?",
            (pothole_id,)
        ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail=f"Pothole {pothole_id} not found")

    pothole       = dict(row)
    subject, body = _build_alert(pothole, message)
    delivered     = _send_email(subject, body)

    alert_id = insert_alert(
        pothole_id  = pothole_id,
        urgency     = pothole.get("urgency_label", ""),
        risk_score  = pothole.get("risk_score", 0),
        borough     = pothole.get("borough", ""),
        street_name = pothole.get("street_name", ""),
        message     = message or subject,
        delivered   = delivered,
    )
    return {
        "status":     "sent" if delivered else "logged",
        "alert_id":   alert_id,
        "pothole_id": pothole_id,
        "delivered":  delivered,
        "sent_at":    datetime.now(timezone.utc).isoformat(),
    }


@router.post("/scan")
async def scan_and_alert(
    min_risk:   float = _AUTO_ALERT_THRESHOLD,
    authorized: bool  = Depends(verify_admin_key),
):
    """Auto-scan open potholes above min_risk that have never been alerted."""
    potholes = get_high_risk_unalerted(min_risk=min_risk, limit=50)
    if not potholes:
        return {"status": "ok", "alerted": 0, "message": "No new high-risk potholes"}

    results = []
    for p in potholes:
        subject, body = _build_alert(p)
        delivered     = _send_email(subject, body)
        alert_id      = insert_alert(
            pothole_id  = p["unique_key"],
            urgency     = p.get("urgency_label", ""),
            risk_score  = p.get("risk_score", 0),
            borough     = p.get("borough", ""),
            street_name = p.get("street_name", ""),
            message     = subject,
            delivered   = delivered,
        )
        results.append({"pothole_id": p["unique_key"],
                        "risk_score": p.get("risk_score"),
                        "alert_id":   alert_id,
                        "delivered":  delivered})
    return {"status": "ok", "alerted": len(results), "alerts": results}


@router.get("/history")
def alert_history(limit: int = 100):
    """Return recent alert history from SQLite."""
    return get_alert_history(limit=limit)


@router.post("/report")
async def report_pothole(pothole_id: str, message: Optional[str] = None):
    """
    Public endpoint for the frontend — no API key required.
    Citizens can report a pothole for DOT attention from the map UI.
    """
    from .database import get_conn as _conn
    with _conn() as conn:
        row = conn.execute(
            f"SELECT {POTHOLE_COLS} FROM potholes WHERE unique_key = ?",
            (pothole_id,)
        ).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail=f"Pothole {pothole_id} not found")

    pothole       = dict(row)
    subject, body = _build_alert(pothole, message)
    delivered     = _send_email(subject, body)

    alert_id = insert_alert(
        pothole_id  = pothole_id,
        urgency     = pothole.get("urgency_label", ""),
        risk_score  = pothole.get("risk_score", 0),
        borough     = pothole.get("borough", ""),
        street_name = pothole.get("street_name", ""),
        message     = message or subject,
        delivered   = delivered,
    )
    return {
        "status":     "reported",
        "alert_id":   alert_id,
        "pothole_id": pothole_id,
        "sent_at":    datetime.now(timezone.utc).isoformat(),
    }