"""
Alert message generation and email delivery for the API layer.
Wraps the same SMTP logic used by alerts.py router.
"""

from __future__ import annotations

import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

SMTP_HOST        = os.getenv("SMTP_HOST",        "smtp.gmail.com")
SMTP_PORT        = int(os.getenv("SMTP_PORT",    "587"))
SMTP_USER        = os.getenv("SMTP_USER",        "")
SMTP_PASSWORD    = os.getenv("SMTP_PASS",        "")
ALERT_RECIPIENT  = os.getenv("ALERT_EMAIL_TO",   "dot.notifications@nyc.gov")
FROM_EMAIL       = os.getenv("ALERT_EMAIL_FROM", SMTP_USER)


def generate_alert_message(pothole: dict, custom_message: Optional[str] = None) -> str:
    return (
        f"[PotholeIQ] {pothole.get('urgency_label','HIGH').upper()} Risk — "
        f"{pothole.get('street_name','Unknown')}, {pothole.get('borough','NYC')}\n\n"
        f"Pothole ID    : {pothole.get('unique_key')}\n"
        f"Days Open     : {int(pothole.get('age_days') or 0)}\n"
        f"Risk Score    : {(pothole.get('risk_score') or 0):.1f}/100\n"
        f"Urgency       : {pothole.get('urgency_label') or 'N/A'}\n"
        f"Nearby Crashes: {pothole.get('nearby_crashes') or 0}\n"
        f"Daily Traffic : {int(pothole.get('traffic_volume') or 0):,} vehicles\n"
        + (f"\nNote: {custom_message}" if custom_message else "")
        + f"\n\nGenerated by PotholeIQ · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )


def send_alert_email(pothole: dict, message: str) -> bool:
    """Send email. Returns True if actually delivered, False if SMTP not configured or failed."""
    if not SMTP_USER or not SMTP_PASSWORD:
        print(f"[ALERT — no SMTP] {message}")
        return False

    msg = MIMEMultipart()
    msg["From"]    = FROM_EMAIL
    msg["To"]      = ALERT_RECIPIENT
    msg["Subject"] = (
        f"[PotholeIQ] Alert — {pothole.get('street_name','Unknown')}, "
        f"{pothole.get('borough','NYC')}"
    )
    msg.attach(MIMEText(message, "plain"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        return True
    except Exception as e:
        print(f"[ALERT email failed] {e}")
        return False
